In [1]:
import numpy as np


In [2]:
import os
os.listdir()

['.ipynb_checkpoints',
 '10thMay - Keyword.ipynb',
 '11th July - Numpy.ipynb',
 '16thMay - Tuple & Dictionary.ipynb',
 '16thMay - Tuple.ipynb',
 '16thMay - Variable.ipynb',
 '17thMay - Set.ipynb',
 '1st July Polymorphism.ipynb',
 '20h June - OOPS.ipynb',
 '21st June - OOPS.ipynb',
 '23rdMay - if & For loop - Jupyter Notebook.html',
 '24th May - Dictionary.ipynb',
 '24th May Lambda-Copy2.ipynb',
 '27th June - OOPS - Types of Inheritance.ipynb',
 '28th June - OOPS - Encapsulation.ipynb',
 '30thMay_Lambda.ipynb',
 '31st May - Exception Handling.ipynb',
 '31st May - File Handling.ipynb',
 '4th July - Pandas - By Sandeep.ipynb',
 '5th July - Pandas.ipynb',
 '6th June Exception Handling.ipynb',
 'animal.xlsx',
 'animals.csv',
 'Basic python (1).ipynb',
 'fil2e.txt',
 'file2.txt',
 'sample.txt',
 'sample2.txt',
 'sample3.txt',
 'Untitled2.ipynb']

In [7]:
import numpy as np
my_list = [1,2,3,4,5]
print(type(my_list))
my_list

<class 'list'>


[1, 2, 3, 4, 5]

# my_arr=np.array(my_list)

print(type(my_arr))
my_arr.shape

In [5]:
#1D
my_arr=np.array([1,23,45,88])

print(type(my_arr))   # 1 Dimension array
my_arr

<class 'numpy.ndarray'>


array([ 1, 23, 45, 88])

In [8]:
#2D 
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
print(type(my_matrix))  # 2d matrix

my_matrix

<class 'list'>


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

2 - D Array (Row,Column)

In [10]:
arr1=np.array(my_matrix)
print(type(arr1))
print(arr1)
arr1.shape

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

In [12]:
arr = np.array([[1,'one'],[99,'two']])
arr.shape

(2, 2)

In [16]:
# It will not include last element
import numpy as np
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [20]:
#Default Data Type is Float
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
#5 Rows 4 Columns
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.ones(3)

array([1., 1., 1.])

In [24]:
# 2 rows 3 Columns
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
# Eye - All diagnol values are 1, other values are zero
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
#Linspace. Initial value =0, last value = 10, 5 is the number containing
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [27]:
#Exclude Endpoint
np.linspace(0,10, endpoint=False)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [28]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [31]:
#Random
# rand - return a sample from the "standard normal" distribution
np.random.rand(5)

array([0.04536904, 0.96121143, 0.04946024, 0.14244746, 0.30916464])

In [33]:
np.random.rand(4,5)

array([[0.92934851, 0.54868386, 0.46071173, 0.7839481 , 0.65439122],
       [0.33534667, 0.49225398, 0.36946724, 0.75542552, 0.82327934],
       [0.3780274 , 0.68618758, 0.32812364, 0.71390647, 0.89846434],
       [0.55749611, 0.6958985 , 0.50407584, 0.1234714 , 0.96124629]])

In [34]:
# Take 2 values randomly
np.random.randn(2)

array([ 2.10873461, -1.69038613])

In [35]:
np.random.randn(5,5)

array([[ 0.24748718,  1.74134685, -0.77139808,  0.12350519, -0.30045672],
       [ 1.52006137, -0.12980877,  1.27341539,  0.80172594, -1.69049046],
       [ 0.63805694,  0.28978792,  0.49931654, -0.66446412,  0.46153404],
       [ 0.23390124, -0.80554487,  1.2272162 , -1.18169468, -2.08536684],
       [-0.40039325, -1.34206945,  0.19984624, -2.03154927,  1.21239803]])

In [39]:
#Randint
np.random.randint(1,100,3)

array([45, 69, 66])

In [37]:
np.random.randint(1,100,10)

array([64, 59, 73, 62, 71, 26,  3, 55, 11, 32])

In [38]:
# 2 rows 4 columns
# number would be between 2 to 8
np.random.randint(2,8, size=(2,4))

array([[2, 6, 2, 7],
       [2, 4, 4, 5]])

# 12th July


In [3]:
import numpy as np
arr = np.arange(0,10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr + arr


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [7]:
arr.mean()

4.5

In [8]:
arr.min()

0

In [9]:
arr.max()

9

In [10]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [15]:
arr.argmin() # Index position where we have , value

0

In [12]:
arr.argmax() # Index position where we have max value

9

In [13]:
arr.all() # If contain 0 in list then it show false

False

In [14]:
arr1 = np.arange(1,10) 
arr1.all()

True

#Pandas

In [16]:
import numpy as np
import  pandas as pd
data=pd.read_csv()
data.head()

TypeError: parser_f() missing 1 required positional argument: 'filepath_or_buffer'

In [20]:
import numpy as np
import pandas as pd
# creating numeric panda series
s = pd.Series([2,4,5,6,9])
print(s)
print(type(s))

0    2
1    4
2    5
3    6
4    9
dtype: int64
<class 'pandas.core.series.Series'>


In [21]:
#Creating a series of charcters
# Notice dtype is object
char_series = pd.Series(['a','b','af'])
char_series

0     a
1     b
2    af
dtype: object

In [25]:
# creating a series of type datetime
date_series = pd.date_range(start = '11-09-2017', end = '12-12-2017')
date_series

DatetimeIndex(['2017-11-09', '2017-11-10', '2017-11-11', '2017-11-12',
               '2017-11-13', '2017-11-14', '2017-11-15', '2017-11-16',
               '2017-11-17', '2017-11-18', '2017-11-19', '2017-11-20',
               '2017-11-21', '2017-11-22', '2017-11-23', '2017-11-24',
               '2017-11-25', '2017-11-26', '2017-11-27', '2017-11-28',
               '2017-11-29', '2017-11-30', '2017-12-01', '2017-12-02',
               '2017-12-03', '2017-12-04', '2017-12-05', '2017-12-06',
               '2017-12-07', '2017-12-08', '2017-12-09', '2017-12-10',
               '2017-12-11', '2017-12-12'],
              dtype='datetime64[ns]', freq='D')

# Indexing Series

In [29]:
print(s)
print(s[3])

0    2
1    4
2    5
3    6
4    9
dtype: int64
6


In [27]:
#print value start from index 2
print(s[2:])

2    5
3    6
4    9
dtype: int64


In [28]:
#print value for index 1 and 3
s[[1,3]]

1    4
3    6
dtype: int64

In [31]:
# Explictly specifying ind
# Index would be a,b,c
pd.Series([4,5,6], index = ['a','b','c'])

a    4
b    5
c    6
dtype: int64

In [32]:
# 
pd.Series(np.array(range(0,10))**2, index = range(1,11))

1      0
2      1
3      4
4      9
5     16
6     25
7     36
8     49
9     64
10    81
dtype: int32

#DataFrame

# DATAFRAME

In [33]:
df = pd.DataFrame({'Name':['Vinay','Kushal','Aman',"Saif"],
                  'Age':[22,25,24,28],
                  'Occupation': ['engineer','doctor','data analyst','teacher']})
df

Name  Age    Occupation
0   Vinay   22      engineer
1  Kushal   25        doctor
2    Aman   24  data analyst
3    Saif   28       teacher

In [36]:
# reading a csv file
market_df = pd.read_csv("train.csv")
market_df.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [37]:
market_df = pd.read_csv("sales.csv")
market_df.head()

Sales Executive      Name Gender  Age   Location  Sales ( in Rs)
0           Emp_1    Mahesh   Male   25  Hyderabad              50
1           Emp_2    Suresh   Male   22  Hyderabad              75
2           Emp_3     Vijay   Male   20  Bangalore              11
3           Emp_4    Ramesh   Male   27  Bangalore              77
4           Emp_5  Jagadish   Male   28     Mumbai              45

In [39]:
market_df = pd.read_csv("sales.csv")
market_df.head(10)

Sales Executive      Name  Gender  Age   Location  Sales ( in Rs)
0           Emp_1    Mahesh    Male   25  Hyderabad              50
1           Emp_2    Suresh    Male   22  Hyderabad              75
2           Emp_3     Vijay    Male   20  Bangalore              11
3           Emp_4    Ramesh    Male   27  Bangalore              77
4           Emp_5  Jagadish    Male   28     Mumbai              45
5           Emp_6    Harish    Male   24  Hyderabad              52
6           Emp_7     Karan    Male   24  Bangalore              26
7           Emp_8      Raju    Male   23     Mumbai              24
8           Emp_9      Maya  Female   24     Mumbai              28
9          Emp_10      Rani  Female   30     Mumbai              31

In [40]:
market_df.head()

Sales Executive      Name Gender  Age   Location  Sales ( in Rs)
0           Emp_1    Mahesh   Male   25  Hyderabad              50
1           Emp_2    Suresh   Male   22  Hyderabad              75
2           Emp_3     Vijay   Male   20  Bangalore              11
3           Emp_4    Ramesh   Male   27  Bangalore              77
4           Emp_5  Jagadish   Male   28     Mumbai              45

In [41]:
market_df.tail()

Sales Executive       Name  Gender  Age   Location  Sales ( in Rs)
15          Emp_16  Aishwarya  Female   24  Bangalore              40
16          Emp_17    Madhavi  Female   29     Mumbai              18
17          Emp_18     Rajini  Female   27     Mumbai              35
18          Emp_19    Haritha  Female   24  Hyderabad              29
19          Emp_20     Swathi  Female   25  Hyderabad              68

market_df.info()

In [43]:
market_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Sales Executive  20 non-null     object
 1   Name             20 non-null     object
 2   Gender           20 non-null     object
 3   Age              20 non-null     int64 
 4   Location         20 non-null     object
 5   Sales ( in Rs)   20 non-null     int64 
dtypes: int64(2), object(4)
memory usage: 1.1+ KB


In [44]:
market_df.describe()

Age  Sales ( in Rs)
count  20.000000       20.000000
mean   24.600000       43.550000
std     2.835861       19.974918
min    19.000000       11.000000
25%    23.750000       28.750000
50%    24.000000       38.000000
75%    26.250000       56.000000
max    30.000000       77.000000

In [45]:
market_df.columns

Index(['Sales Executive', 'Name', 'Gender', 'Age', 'Location',
       'Sales ( in Rs)'],
      dtype='object')

In [46]:
market_df.shape

(20, 6)

In [47]:
market_df.values

array([['Emp_1', 'Mahesh', 'Male', 25, 'Hyderabad', 50],
       ['Emp_2', 'Suresh', 'Male', 22, 'Hyderabad', 75],
       ['Emp_3', 'Vijay', 'Male', 20, 'Bangalore', 11],
       ['Emp_4', 'Ramesh', 'Male', 27, 'Bangalore', 77],
       ['Emp_5', 'Jagadish', 'Male', 28, 'Mumbai', 45],
       ['Emp_6', 'Harish', 'Male', 24, 'Hyderabad', 52],
       ['Emp_7', 'Karan', 'Male', 24, 'Bangalore', 26],
       ['Emp_8', 'Raju', 'Male', 23, 'Mumbai', 24],
       ['Emp_9', 'Maya', 'Female', 24, 'Mumbai', 28],
       ['Emp_10', 'Rani', 'Female', 30, 'Mumbai', 31],
       ['Emp_11', 'Lakshmi', 'Female', 19, 'Bangalore', 36],
       ['Emp_12', 'Roopa', 'Female', 24, 'Hyderabad', 72],
       ['Emp_13', 'Sravya', 'Female', 26, 'Hyderabad', 69],
       ['Emp_14', 'Sruthi', 'Female', 26, 'Hyderabad', 51],
       ['Emp_15', 'Swetha', 'Female', 21, 'Bangalore', 34],
       ['Emp_16', 'Aishwarya', 'Female', 24, 'Bangalore', 40],
       ['Emp_17', 'Madhavi', 'Female', 29, 'Mumbai', 18],
       ['Emp_18', 'Raj

# Indices

In [48]:
market_df.head()

Sales Executive      Name Gender  Age   Location  Sales ( in Rs)
0           Emp_1    Mahesh   Male   25  Hyderabad              50
1           Emp_2    Suresh   Male   22  Hyderabad              75
2           Emp_3     Vijay   Male   20  Bangalore              11
3           Emp_4    Ramesh   Male   27  Bangalore              77
4           Emp_5  Jagadish   Male   28     Mumbai              45

In [50]:
market_df.set_index('Ord_id', inplace = True)
market_df.head()

KeyError: "None of ['Ord_id'] are in the columns"

In [49]:
market_df.sort_values(by='Shipping_Cost', ascending = False).head()

KeyError: 'Shipping_Cost'